const slides = Array.from({length:23},(_,i)=>`assets/slides/page-${String(i+1).padStart(2,'0')}.jpg`);

const modules = [
  {id:'presentation',title:'Презентация партии',desc:'23 слайда: история, программа, структура и возможности.',time:'7–10 минут',icon:'▶',accent:'#43d1c4'},
  {id:'deg',title:'Что такое ДЭГ',desc:'Как работает дистанционное электронное голосование и что важно не перепутать.',time:'3 минуты',icon:'✓',accent:'#ff5165'},
  {id:'demin',title:'Александр Дёмин',desc:'Краткая биография, роль в Госдуме и основные темы работы.',time:'3 минуты',icon:'Д',accent:'#f07e23'},
  {id:'region',title:'Свердловское отделение',desc:'Команда, уровни представительства и региональный контекст.',time:'4 минуты',icon:'66',accent:'#8bd450'},
  {id:'party',title:'Главное о партии',desc:'Факты и позиции, которые должен уверенно знать представитель команды.',time:'5 минут',icon:'#',accent:'#c997ff'}
];

const sourceLinks = `<div class="sources"><b>Источники:</b> <a href="https://p.newpeople.ru/" target="_blank" rel="noreferrer">официальный сайт партии</a> · <a href="https://duma.gov.ru/duma/factions/72100035/" target="_blank" rel="noreferrer">фракция в Госдуме</a> · <a href="https://ekb.newpeople.ru/" target="_blank" rel="noreferrer">региональное отделение</a></div>`;

const galleries = {
  deg: [['assets/gallery/deg-01.jpg','Электронное голосование: работа с цифровым бюллетенем'],['assets/gallery/deg-02.jpg','Дистанционное участие в процедуре голосования'],['assets/gallery/deg-03.jpg','Интерфейс электронного голосования'],['assets/gallery/deg-04.jpg','Голосование через защищённую цифровую систему']],
  demin: [['assets/gallery/demin-01.jpg','Александр Дёмин'],['assets/gallery/demin-02.jpg','Александр Дёмин на рабочей встрече в Госдуме'],['assets/gallery/demin-03.jpg','Первое заседание Государственной Думы VIII созыва'],['assets/gallery/demin-04.jpg','Здание Государственной Думы в Москве']],
  region: [['assets/gallery/region-01.jpg','Екатеринбург: городской пруд и деловой центр'],['assets/gallery/region-02.jpg','Панорама Екатеринбурга'],['assets/gallery/region-03.jpg','Екатеринбург-Сити'],['assets/gallery/region-04.jpg','Современный городской центр Екатеринбурга']],
  party: [['assets/gallery/party-01.jpg','Фракция «Новые люди» в Государственной Думе'],['assets/gallery/party-02.jpg','Партийная агитационная кампания'],['assets/gallery/party-03.png','Флаг партии «Новые люди»'],['assets/gallery/party-04.png','Логотип партии «Новые люди»']]
};

function galleryMarkup(id){const items=galleries[id];if(!items)return '';const note=id==='deg'?' Электронное голосование показано на иллюстративных примерах; интерфейс российского ДЭГ может отличаться.':'';return `<section class="photo-section" aria-label="Фотогалерея"><div class="photo-heading"><div><span>ВИЗУАЛЬНЫЙ КОНТЕКСТ</span><h2>Галерея раздела</h2></div><p>4 изображения · нажмите, чтобы открыть крупнее</p></div><div class="photo-grid">${items.map(([src,caption],i)=>`<figure class="photo-card ${src.endsWith('.png')?'is-logo':''} ${i===0?'featured':''}"><a href="${src}" target="_blank" rel="noreferrer"><img src="${src}" alt="${caption}" loading="lazy"></a><figcaption><b>${String(i+1).padStart(2,'0')}</b><span>${caption}</span></figcaption></figure>`).join('')}</div><p class="photo-credit">Изображения: Wikimedia Commons.${note}</p></section>`}

const lessons = {
  presentation: () => `<header class="lesson-title"><span class="icon">▶</span><div><h1>Презентация партии</h1><p>Листайте слайды или выберите нужный номер. Изображения встроены в приложение и доступны без интернета.</p></div></header><div class="slide-shell"><div class="slide-frame"><img id="slide-image" src="${slides[0]}" alt="Слайд 1"></div><div class="slide-controls"><button id="prev-slide" aria-label="Предыдущий слайд">←</button><span class="slide-dots"><b id="slide-current">1</b> / 23</span><button id="next-slide" aria-label="Следующий слайд">→</button></div><div class="slide-thumbs">${slides.map((s,i)=>`<button class="slide-thumb ${i===0?'active':''}" data-slide="${i}" aria-label="Слайд ${i+1}"><img src="${s}" alt=""></button>`).join('')}</div></div>`,
  deg: () => `<header class="lesson-title"><span class="icon">✓</span><div><h1>Что такое ДЭГ</h1><p>Дистанционное электронное голосование — один из способов участия в выборах через интернет, если оно применяется на конкретных выборах и доступно избирателю.</p></div></header><div class="fact-strip"><div class="fact"><b>Онлайн</b>голосование проходит на официальной государственной платформе</div><div class="fact"><b>Заранее</b>порядок и сроки определяются для конкретной кампании</div><div class="fact"><b>Добровольно</b>избиратель сам выбирает доступный способ голосования</div></div><div class="content-grid"><section class="info-card"><h2>Как это устроено</h2><ul><li>Избиратель проходит идентификацию через подтверждённую государственную учётную запись.</li><li>При необходимости заранее подаёт заявление на участие.</li><li>В дни голосования получает доступ к электронному бюллетеню.</li><li>Система учитывает голос без раскрытия выбора посторонним.</li></ul></section><section class="info-card"><h2>Что важно говорить точно</h2><ul><li>ДЭГ проводится не автоматически на всех выборах и не во всех регионах.</li><li>Сроки подачи заявления и площадку всегда нужно проверять в официальных источниках.</li><li>Нельзя просить человека показывать, за кого он проголосовал.</li><li>Нельзя обещать регистрацию или доступ без проверки официальных условий.</li></ul></section><section class="info-card wide"><div class="callout"><b>Короткая формулировка:</b> «ДЭГ — это возможность проголосовать дистанционно через официальную государственную систему. Доступность и сроки регистрации зависят от конкретных выборов».</div></section></div><div class="check"><h3>Самопроверка</h3><label><input type="radio" name="q-deg" value="0"> ДЭГ всегда доступно каждому без регистрации</label><label><input type="radio" name="q-deg" value="1"> Условия ДЭГ нужно проверять для конкретных выборов</label><button class="quiz-button" data-answer="1">Проверить</button><div class="check-result"></div></div><div class="sources"><a href="https://vybory.gov.ru/" target="_blank" rel="noreferrer">Официальная информация ЦИК России</a></div>`,
  demin: () => `<header class="lesson-title"><span class="icon">Д</span><div><h1>Александр Дёмин</h1><p>Федеральный депутат и один из ключевых представителей предпринимательской повестки партии.</p></div></header><div class="fact-strip"><div class="fact"><b>1988</b>родился 23 сентября в Ростове-на-Дону</div><div class="fact"><b>2021</b>избран депутатом Государственной Думы VIII созыва</div><div class="fact"><b>МСП</b>председатель профильного комитета Госдумы</div></div><div class="content-grid"><section class="info-card"><h2>Текущая роль</h2><p>Депутат фракции «Новые люди», председатель Комитета Государственной Думы по малому и среднему предпринимательству, заместитель руководителя фракции.</p></section><section class="info-card"><h2>Основные темы</h2><div class="tag-row"><span class="tag">малый бизнес</span><span class="tag">самозанятые</span><span class="tag">кредитование</span><span class="tag">регуляторная нагрузка</span><span class="tag">цифровая экономика</span></div></section><section class="info-card wide"><h2>Что можно назвать</h2><ul><li>Работа над мерами финансовой поддержки малого и среднего бизнеса.</li><li>Предложения по кредитным каникулам, доступности финансирования и снижению административного давления.</li><li>Участие в развитии партийной сети: до избрания в Госдуму руководил масштабированием штабов партии в регионах.</li><li>В 2026 году выдвинут партией от Свердловской области.</li></ul></section><section class="info-card wide"><div class="callout"><b>Важно:</b> не приписывайте депутату единоличное авторство коллективных законов. Корректные формулировки: «участвовал в разработке», «выступил с предложением», «комитет под его руководством работал над…».</div></section></div>${sourceLinks}`,
  region: () => `<header class="lesson-title"><span class="icon">66</span><div><h1>Свердловское отделение</h1><p>Региональная команда представляет партию на федеральном, областном и муниципальном уровнях.</p></div></header><div class="content-grid"><section class="info-card"><h2>Ключевые лица</h2><ul><li><b>Ирина Виноградова</b> — руководитель регионального отделения.</li><li><b>Рант Краев</b> — руководитель фракции в Законодательном собрании области.</li><li><b>Сергей Козин</b> — депутат Законодательного собрания.</li><li><b>Дмитрий Дума</b> — депутат Екатеринбургской городской думы.</li></ul></section><section class="info-card"><h2>Уровни работы</h2><ul><li>Федеральный: депутаты Государственной Думы.</li><li>Региональный: Законодательное собрание Свердловской области.</li><li>Муниципальный: городские думы и местные команды.</li><li>Проектный: общественные инициативы и тематические комитеты.</li></ul></section><section class="info-card wide"><h2>Электоральный контекст из презентации</h2><div class="fact-strip"><div class="fact"><b>9,19%</b>Заксобрание области, 2021</div><div class="fact"><b>8,23%</b>Госдума, 2021</div><div class="fact"><b>8,5%</b>Екатеринбургская гордума, 2023</div></div><p>Эти цифры относятся к конкретным кампаниям и не являются текущим рейтингом партии.</p></section><section class="info-card wide"><h2>Что предлагает участие в команде</h2><div class="tag-row"><span class="tag">первичные отделения</span><span class="tag">экспертные комитеты</span><span class="tag">общественные проекты</span><span class="tag">наблюдение</span><span class="tag">кандидатский трек</span></div></section></div>${sourceLinks}`,
  party: () => `<header class="lesson-title"><span class="icon">#</span><div><h1>Главное о партии</h1><p>Минимальная фактологическая база, которую нужно знать без подсказки.</p></div></header><div class="fact-strip"><div class="fact"><b>2020</b>партия основана 1 марта</div><div class="fact"><b>5,32%</b>результат на выборах в Госдуму 2021 года</div><div class="fact"><b>15</b>депутатов во фракции на момент подготовки модуля</div></div><div class="content-grid"><section class="info-card"><h2>Кто основал</h2><p><b>Алексей Нечаев</b> — основатель партии и руководитель фракции в Госдуме. Партия получила государственную регистрацию в 2020 году.</p></section><section class="info-card"><h2>Как позиционируется</h2><p>«Партия здравого смысла»: развитие вместо запретов, доверие к людям, поддержка предпринимательства, современные технологии и сильные регионы.</p></section><section class="info-card wide"><h2>Программа 2026: основные направления</h2><div class="tag-row"><span class="tag">доверие и достоинство</span><span class="tag">сильные регионы</span><span class="tag">доступное жильё</span><span class="tag">образование</span><span class="tag">самозанятые и стартапы</span><span class="tag">конкуренция</span><span class="tag">прозрачный бюджет</span><span class="tag">разумное регулирование интернета</span></div></section><section class="info-card"><h2>Федеральные лица</h2><ul><li>Алексей Нечаев</li><li>Владислав Даванков</li><li>Сардана Авксентьева</li></ul></section><section class="info-card"><h2>Правило точности</h2><p>Разделяйте три формулировки: партия <b>предлагает</b>, депутаты <b>внесли законопроект</b>, Госдума <b>приняла закон</b>. Это разные стадии.</p></section><section class="info-card wide"><div class="callout"><b>Если не знаете ответа:</b> не придумывайте. Скажите, что уточните информацию по официальным источникам. Фактическая точность важнее уверенного, но неверного ответа.</div></section></div><div class="check"><h3>Самопроверка</h3><label><input type="radio" name="q-party" value="0"> Партия впервые прошла в Госдуму в 2016 году</label><label><input type="radio" name="q-party" value="1"> Партия впервые прошла в Госдуму в 2021 году</label><button class="quiz-button" data-answer="1">Проверить</button><div class="check-result"></div></div>${sourceLinks}`
};

const grid=document.querySelector('#module-grid');
const nav=document.querySelector('#main-nav');
grid.innerHTML=modules.map((m,i)=>`<button class="module-card" data-module="${m.id}" style="--accent:${m.accent}"><span class="num">${i+1}</span><h2>${m.title}</h2><p>${m.desc}</p><span class="time">${m.time} →</span></button>`).join('');
nav.innerHTML=`<button data-home>Главная</button>`+modules.map((m,i)=>`<button data-module="${m.id}">${i+1}. ${m.title}</button>`).join('');

const catalog=document.querySelector('#catalog'),lesson=document.querySelector('#lesson'),content=document.querySelector('#lesson-content');
function showCatalog(){catalog.classList.add('active');lesson.classList.remove('active');history.replaceState(null,'','#catalog');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));window.scrollTo(0,0)}
function openModule(id){const index=modules.findIndex(m=>m.id===id);if(index<0)return;catalog.classList.remove('active');lesson.classList.add('active');content.innerHTML=lessons[id]();const lessonTitle=content.querySelector('.lesson-title');if(lessonTitle&&galleries[id])lessonTitle.insertAdjacentHTML('afterend',galleryMarkup(id));document.querySelector('#lesson-number').textContent=`Модуль ${index+1} из ${modules.length}`;document.querySelector('#progress-bar').style.width=`${(index+1)/modules.length*100}%`;document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.module===id));history.replaceState(null,'',`#${id}`);wireLesson(id);document.querySelector('.nav').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false');window.scrollTo(0,0)}
function wireLesson(id){if(id==='presentation'){let current=0;const image=document.querySelector('#slide-image'),num=document.querySelector('#slide-current'),thumbs=[...document.querySelectorAll('.slide-thumb')];const set=n=>{current=(n+slides.length)%slides.length;image.src=slides[current];image.alt=`Слайд ${current+1}`;num.textContent=current+1;thumbs.forEach((t,i)=>t.classList.toggle('active',i===current))};document.querySelector('#prev-slide').onclick=()=>set(current-1);document.querySelector('#next-slide').onclick=()=>set(current+1);thumbs.forEach(t=>t.onclick=()=>set(Number(t.dataset.slide)))}document.querySelectorAll('.quiz-button').forEach(btn=>btn.onclick=()=>{const box=btn.closest('.check'),picked=box.querySelector('input:checked'),out=box.querySelector('.check-result');if(!picked){out.textContent='Выберите ответ.';return}out.textContent=picked.value===btn.dataset.answer?'Верно.':'Пока нет — перечитайте блок выше.';out.style.color=picked.value===btn.dataset.answer?'#08756e':'#b3293b'})}
document.addEventListener('click',e=>{const mod=e.target.closest('[data-module]');if(mod)openModule(mod.dataset.module);if(e.target.closest('[data-home]')||e.target.closest('.back-button'))showCatalog()});
document.querySelector('.menu-button').onclick=e=>{const open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};
const initial=location.hash.slice(1);if(modules.some(m=>m.id===initial))openModule(initial);else showCatalog();
